### ISSUE TITLE
jQuery Local Fallback?

### ISSUE THREAD

**Issue by jpdevries** [mischaandrews/allihop#1]
Accessibility wise, CDNs aren't always reachable. They could be blocked, down, or the user could be behind some sort of firewall. CDNs offer great accessibility in terms of leveraging the browser cache across multiple domains, so for this reason H5BP uses a clever CDN with local fallback technique.
https://github.com/h5bp/html5-boilerplate/blob/master/dist/index.html#L25

It should be noted that since `document.write` is kind of being phased out the h5bp project hasn't decided on how to update this technique yet.

https://github.com/h5bp/html5-boilerplate/issues/1896

**Comment by mischaandrews** [comment]
Ah thanks, I'll check that out!

**Comment by mischaandrews** [comment]
That works brilliantly, thank you!
